[package]
name = "rustlib"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

# Optimizations for release profile
[profile.release]
opt-level = "s"
lto = true
strip = true
codegen-units = 1

[dependencies]
